services:
  - type: web
    name: pids-backend
    env: docker
    plan: free
    autoDeploy: true
    dockerfilePath: ./Dockerfile

    envVars:
      # ---- Core ----
      - key: DATABASE_URL
        fromDatabase:
          name: pids-postgres
          property: connectionString
      - key: PORT
        value: "10000"
      - key: PYTHONUNBUFFERED
        value: "1"

      # ---- Admin/API auth (matches backend code) ----
      - key: API_KEY_PIDS
        value: "Yj@zpmbdb"            # header: X-API-KEY

      # ---- CORS (locked for safety; Tkinter won't use CORS anyway) ----
      - key: ALLOWED_ORIGINS
        value: https://pids-backend.onrender.com

      # ---- Telegram webhook hardening ----
      - key: TG_WEBHOOK_SECRET
        value: "Yj@zisr15#9910570928%ziso3&zpmbdb^o4tenrev*o4nm&ziso6$zmmuser%mmbe"  # replace with a strong secret (>=64 chars)
      - key: PUBLIC_WEBHOOK_URL
        value: "https://pids-backend.onrender.com/webhook"

      # ---- Optional allowlists (recommended) ----
      # Comma-separated. Keep quotes if using negative IDs.
      - key: ALLOWED_CHAT_IDS
        value: "-4832290037,-4873858885,-4853569789,-4901728134,-4927807764,-4909439914,-4975573108" # e.g. "-1001111111111,-1002222222222"
      - key: ALLOWED_USER_IDS
        value: ""                    # e.g. "12345678,987654321"

      # ---- Media + rate limit tuning (optional) ----
      - key: MAX_MEDIA_BYTES
        value: "10485760"             # 5 MiB. For 10 MiB use 10485760
      # - key: RATE_LIMIT_STORAGE_URI
      #   value: "rediss://default:PASS@HOST:PORT/0"  # Upstash/Redis if you add it

      # ---- Seeding toggle ----
      - key: SEED_ON_START
        value: "1"   # set to "0" after first successful seed if you want

      # ---- From settings.json ----
      - key: SEED_BOT_TOKEN
        value: "123456:ABC-BotTokenHere"
      - key: SEED_ALERT_SOUND
        value: "true"
      - key: SEED_TIMEOUT
        value: "10"

      # ---- From group_mapping.json ----
      - key: SEED_GROUP_MAPPINGS_JSON
        value: |
          [
            {
              "start_ch": 285.0,
              "end_ch": 326.0,
              "group_name": "Group1",
              "chat_id": "-1001111111111",
              "time_window": "day"
            },
            {
              "start_ch": 326.0,
              "end_ch": 367.0,
              "group_name": "Group2",
              "chat_id": "-1002222222222",
              "time_window": "day"
            },
            {
              "start_ch": 367.0,
              "end_ch": 405.0,
              "group_name": "Group3",
              "chat_id": "-1003333333333",
              "time_window": "day"
            },
            {
              "start_ch": 405.0,
              "end_ch": 444.0,
              "group_name": "Group4",
              "chat_id": "-1004444444444",
              "time_window": "day"
            },
            {
              "start_ch": 285.0,
              "end_ch": 340.0,
              "group_name": "Group5",
              "chat_id": "-1005555555555",
              "time_window": "night"
            },
            {
              "start_ch": 340.0,
              "end_ch": 388.0,
              "group_name": "Group6",
              "chat_id": "-1006666666666",
              "time_window": "night"
            },
            {
              "start_ch": 388.0,
              "end_ch": 444.0,
              "group_name": "Group7",
              "chat_id": "-1007777777777",
              "time_window": "night"
            }
          ]

      # ---- From linewalkers.json ----
      - key: SEED_LINEWALKERS_JSON
        value: |
          [
            { "start_ch": 285.0, "end_ch": 297.0, "line_walker": "" },
            { "start_ch": 297.0, "end_ch": 311.0, "line_walker": ""},
            { "start_ch": 311.0, "end_ch": 318.0, "line_walker": ""},
            { "start_ch": 318.0, "end_ch": 325.0, "line_walker": "" },
            { "start_ch": 325.0, "end_ch": 333.0, "line_walker": ""},
            { "start_ch": 333.0, "end_ch": 340.0, "line_walker": "" },
            { "start_ch": 340.0, "end_ch": 354.0, "line_walker": ""},
            { "start_ch": 354.0, "end_ch": 367.0, "line_walker": "" },
            { "start_ch": 367.0, "end_ch": 377.0, "line_walker": "" },
            { "start_ch": 377.0, "end_ch": 385.0, "line_walker": "" },
            { "start_ch": 385.0, "end_ch": 393.0, "line_walker": ""},
            { "start_ch": 393.0, "end_ch": 405.0, "line_walker": "" },
            { "start_ch": 405.0, "end_ch": 415.0, "line_walker": "" },
            { "start_ch": 415.0, "end_ch": 423.0, "line_walker": "" },
            { "start_ch": 423.0, "end_ch": 429.0, "line_walker": ""},
            { "start_ch": 429.0, "end_ch": 436.0, "line_walker": "" },
            { "start_ch": 436.0, "end_ch": 444.0, "line_walker": ""}
          ]

      # ---- From supervisors.json ----
      - key: SEED_SUPERVISORS_JSON
        value: |
          [
            { "start_ch": 285.0, "end_ch": 326.0, "supervisor": "" },
            { "start_ch": 326.0, "end_ch": 367.0, "supervisor": "" },
            { "start_ch": 367.0, "end_ch": 405.0, "supervisor": "" },
            { "start_ch": 405,   "end_ch": 443.33, "supervisor": "" }
          ]

      # ---- From npv.json ----
      - key: SEED_NPV_JSON
        value: |
          [
            { "start_ch": 285.0, "end_ch": 340.0, "npv": "NPV-1" },
            { "start_ch": 340.0, "end_ch": 388.0, "npv": "NPV-2" },
            { "start_ch": 388.0, "end_ch": 443.33, "npv": "NPV-3" }
          ]

databases:
  - name: pids-postgres
    plan: free


