services:
  - type: web
    name: pids-backend
    env: docker
    plan: free
    autoDeploy: true
    dockerfilePath: ./Dockerfile
    envVars:
      # ---- Core ----
      - key: DATABASE_URL
        fromDatabase:
          name: pids-postgres
          property: connectionString
      - key: PORT
        value: "10000"
      - key: PYTHONUNBUFFERED
        value: "1"

      # ---- Admin/API auth (matches backend code) ----
      - key: API_KEY_PIDS
        value: "Yj@zisr15"
      - key: CLIENT_ID
        value: "hpclkrs36"
      - key: HMAC_SECRET
        value: "Gf7yQm8WxPz9Hk1Lr3nVb4Cs5Jt2Yd6Uq8p0Rm1Xv4s9Tz3Bv5c6Lp7Nd8Qf1Wg3"

      # Fernet encryption key (REQUIRED by backend)
      - key: APP_FERNET_KEY
        value: "Eo1NB3HmFdAXILZ_f0-f-DHDv7yli6OwvYm9KfhfjM8="

      # Optional: unlock secret for /admin/unlock
      - key: APP_UNLOCK_SECRET
        value: "hpcl@krsziso3"

      # ---- CORS ----
      - key: ALLOWED_ORIGINS
        value: "https://pids-backend.onrender.com"

      # ---- Telegram webhook hardening ----
      - key: TELEGRAM_WEBHOOK_SECRET
        value: "mA9vRr2Uda4X8uT3_QyVxK0tWlZbOqNkF9b7sJeKpD1gHf6z"
      - key: PUBLIC_WEBHOOK_URL
        value: "https://pids-backend.onrender.com/webhook"

      # ---- Optional allowlists (recommended) ----
      - key: ALLOWED_CHAT_IDS
        value: "-4832290037,-4873858885,-4853569789,-4901728134,-4927807764,-4909439914,-4975573108"
      - key: ALLOWED_USER_IDS
        value: ""

      # ---- Media + rate limit tuning (optional) ----
      - key: MAX_MEDIA_BYTES
        value: "10485760"

      # ---- Seeding toggle ----
      - key: SEED_ON_START
        value: "1"

      # ---- From settings.json ----
      - key: SEED_BOT_TOKEN
        value: "123456:ABC-BotTokenHere"
      - key: SEED_ALERT_SOUND
        value: "true"
      - key: SEED_TIMEOUT
        value: "10"
      - key: SEED_CLIENT_ID
        value: "hpclkrs36"

      # ---- From group_mapping.json ----
      - key: SEED_GROUP_MAPPINGS_JSON
        value: |
          [ ... your group mappings here ... ]

      # ---- From linewalkers.json ----
      - key: SEED_LINEWALKERS_JSON
        value: |
          [ ... your linewalker mappings here ... ]

      # ---- From supervisors.json ----
      - key: SEED_SUPERVISORS_JSON
        value: |
          [ ... your supervisor mappings here ... ]

      # ---- From npv.json ----
      - key: SEED_NPV_JSON
        value: |
          [ ... your npv mappings here ... ]

databases:
  - name: pids-postgres
    plan: free

